/**
 * Demo persona + helpers for the frontend-only admin pages. The real admin
 * session replaces these when the backend pass wires Supabase/role guards.
 *
 * Deliberately NOT "use client" — it is plain static data, so server
 * components can import it too (e.g. to redirect /teacher/home -> /1).
 */

export const dummyGuruData = {
  name: "Bu Dewi Lestari",
  email: "admin@grafidu.sch.id",
  mapel: "Bahasa Indonesia",
  kkm: 80,
  dataKelas: [
    {
      id: 1,
      kelas: "XI RPL B",
      totalMurid: 32,
      materi: [
        {
          id: 1,
          title: "Belajar Teks Eksposisi",
          desc: "Mengenal teks eksposisi sebagai teks yang bertujuan menjelaskan suatu peristiwa atau gagasan secara sistematis. Materi ini membahas tesis, rangkaian argumen, dan penegasan ulang, disertai contoh teks tentang isu lingkungan di sekitar sekolah.",
          attachedFiles: ["/materi/eksposisi-modul.pdf", "https://kemdikbud.go.id/teks-eksposisi"],
        },
        {
          id: 2,
          title: "Unsur Intrinsik Cerpen",
          desc: "Mempelajari lima unsur intrinsik cerpen — tokoh, penokohan, latar, konflik, dan amanat — beserta cara mengidentifikasi setiap unsur pada kutipan cerita pendek.",
          attachedFiles: ["/materi/cerpen-unsur.pdf", "/materi/cerpen-kisah-di-sekolah.docx"],
        },
        {
          id: 3,
          title: "Teks Pidato Persuasif",
          desc: "Struktur pembuka, isi, dan penutup teks pidato persuasif, disertai teknik kebahasaan persuasif dan cara menyusun data yang kuat untuk membahas isu lingkungan.",
          attachedFiles: ["https://id.wikipedia.org/wiki/Pidato_persuasif"],
        },
        {
          id: 4,
          title: "Membuat Resensi Buku",
          desc: "Panduan menulis resensi: identitas buku, sinopsis, kelebihan, dan kekurangan, serta cara memberi rekomendasi yang jujur berdasarkan pembacaan utuh.",
          attachedFiles: ["/materi/resensi-panduan.pdf", "/materi/contoh-resensi.pdf"],
        },
      ],
      tugas: [
        {
          id: 1,
          name: "Menulis Teks Eksposisi",
          ditugaskan: "20 Agustus 2026",
          deadline: "10 September 2026",
          deskripsi:
            "Susun sebuah teks eksposisi dengan tema bebas yang berkaitan dengan isu pendidikan di sekitar sekolah. Teks harus memuat tesis di paragraf pembuka, rangkaian argumen yang tersusun logis, dan penegasan ulang di paragraf penutup. Gunakan kalimat efektif dan kutipan dari sumber yang kredibel, minimal tiga sumber berbeda. Kumpulkan dalam format dokumen (.pdf atau .docx), minimal 350 kata.",
          completed: false,
          muridSelesai: 16,
          pengumpulan: [
            { muridId: 1, tanggal: "20 Agustus 2026" },
            { muridId: 2, tanggal: "21 Agustus 2026" },
            { muridId: 3, tanggal: "22 Agustus 2026" },
            { muridId: 4, tanggal: "23 Agustus 2026" },
            { muridId: 5, tanggal: "25 Agustus 2026" },
            { muridId: 6, tanggal: "26 Agustus 2026" },
            { muridId: 7, tanggal: "27 Agustus 2026" },
            { muridId: 8, tanggal: "29 Agustus 2026" },
            { muridId: 9, tanggal: "30 Agustus 2026" },
            { muridId: 10, tanggal: "31 Agustus 2026" },
            { muridId: 11, tanggal: "2 September 2026" },
            { muridId: 12, tanggal: "3 September 2026" },
            { muridId: 13, tanggal: "4 September 2026" },
            { muridId: 14, tanggal: "6 September 2026" },
            { muridId: 15, tanggal: "7 September 2026" },
            { muridId: 16, tanggal: "8 September 2026" },
          ],
        },
        {
          id: 2,
          name: "Analisis Unsur Intrinsik Cerpen",
          ditugaskan: "22 Juli 2026",
          deadline: "12 Agustus 2026",
          deskripsi:
            "Baca satu cerpen yang ditentukan guru, lalu identifikasi kelima unsur intrinsik - tokoh, penokohan, latar, konflik, dan amanat. Untuk setiap unsur, sertakan kutipan kalimat dari cerpen sebagai bukti dan satu kalimat penjelasan. Tulis analisis dalam bentuk paragraf, bukan poin-poin, minimal 300 kata.",
          completed: true,
          muridSelesai: 32,
          pengumpulan: [
            { muridId: 8, tanggal: "22 Juli 2026" },
            { muridId: 9, tanggal: "22 Juli 2026" },
            { muridId: 10, tanggal: "23 Juli 2026" },
            { muridId: 11, tanggal: "23 Juli 2026" },
            { muridId: 12, tanggal: "24 Juli 2026" },
            { muridId: 13, tanggal: "25 Juli 2026" },
            { muridId: 14, tanggal: "25 Juli 2026" },
            { muridId: 15, tanggal: "26 Juli 2026" },
            { muridId: 16, tanggal: "27 Juli 2026" },
            { muridId: 17, tanggal: "27 Juli 2026" },
            { muridId: 18, tanggal: "28 Juli 2026" },
            { muridId: 19, tanggal: "29 Juli 2026" },
            { muridId: 20, tanggal: "29 Juli 2026" },
            { muridId: 21, tanggal: "30 Juli 2026" },
            { muridId: 22, tanggal: "31 Juli 2026" },
            { muridId: 23, tanggal: "31 Juli 2026" },
            { muridId: 24, tanggal: "1 Agustus 2026" },
            { muridId: 25, tanggal: "2 Agustus 2026" },
            { muridId: 26, tanggal: "2 Agustus 2026" },
            { muridId: 27, tanggal: "3 Agustus 2026" },
            { muridId: 28, tanggal: "4 Agustus 2026" },
            { muridId: 29, tanggal: "4 Agustus 2026" },
            { muridId: 30, tanggal: "5 Agustus 2026" },
            { muridId: 31, tanggal: "6 Agustus 2026" },
            { muridId: 32, tanggal: "6 Agustus 2026" },
            { muridId: 1, tanggal: "7 Agustus 2026" },
            { muridId: 2, tanggal: "8 Agustus 2026" },
            { muridId: 3, tanggal: "8 Agustus 2026" },
            { muridId: 4, tanggal: "9 Agustus 2026" },
            { muridId: 5, tanggal: "10 Agustus 2026" },
            { muridId: 6, tanggal: "10 Agustus 2026" },
            { muridId: 7, tanggal: "11 Agustus 2026" },
          ],
        },
        {
          id: 3,
          name: "Membuat Teks Pidato Persuasif",
          ditugaskan: "20 Agustus 2026",
          deadline: "10 September 2026",
          deskripsi:
            "Siswa membuat teks pidato persuasif dengan tema bebas yang berkaitan dengan isu lingkungan di sekitar sekolah. Pidato harus memuat struktur pembuka, isi, dan penutup, serta minimal tiga argumen yang didukung data atau fakta. Kumpulkan dalam format dokumen (.pdf atau .docx), minimal 400 kata.",
          completed: true,
          muridSelesai: 27,
          pengumpulan: [
            { muridId: 1, tanggal: "20 Agustus 2026" },
            { muridId: 2, tanggal: "20 Agustus 2026" },
            { muridId: 3, tanggal: "21 Agustus 2026" },
            { muridId: 4, tanggal: "21 Agustus 2026" },
            { muridId: 5, tanggal: "22 Agustus 2026" },
            { muridId: 6, tanggal: "22 Agustus 2026" },
            { muridId: 7, tanggal: "22 Agustus 2026" },
            { muridId: 8, tanggal: "23 Agustus 2026" },
            { muridId: 9, tanggal: "24 Agustus 2026" },
            { muridId: 10, tanggal: "25 Agustus 2026" },
            { muridId: 11, tanggal: "26 Agustus 2026" },
            { muridId: 12, tanggal: "27 Agustus 2026" },
            { muridId: 13, tanggal: "28 Agustus 2026" },
            { muridId: 14, tanggal: "28 Agustus 2026" },
            { muridId: 15, tanggal: "29 Agustus 2026" },
            { muridId: 16, tanggal: "30 Agustus 2026" },
            { muridId: 17, tanggal: "31 Agustus 2026" },
            { muridId: 18, tanggal: "1 September 2026" },
            { muridId: 19, tanggal: "2 September 2026" },
            { muridId: 20, tanggal: "3 September 2026" },
            { muridId: 21, tanggal: "3 September 2026" },
            { muridId: 22, tanggal: "4 September 2026" },
            { muridId: 23, tanggal: "5 September 2026" },
            { muridId: 24, tanggal: "6 September 2026" },
            { muridId: 25, tanggal: "7 September 2026" },
            { muridId: 26, tanggal: "8 September 2026" },
            { muridId: 27, tanggal: "9 September 2026" },
          ],
        },
        {
          id: 4,
          name: "Membuat Resensi Buku",
          ditugaskan: "18 Agustus 2026",
          deadline: "1 September 2026",
          deskripsi:
            "Tulis resensi terhadap buku fiksi pilihanmu. Resensi wajib memuat identitas buku, sinopsis, penilaian atas isi dan kegunaan, serta komentar evaluatif terhadap kebahasaan dan penerbit. Sertakan minimal tiga kutipan dari buku yang kamu kutip beserta nomor halaman. Minimal 400 kata.",
          completed: true,
          muridSelesai: 31,
          pengumpulan: [
            { muridId: 22, tanggal: "18 Agustus 2026" },
            { muridId: 23, tanggal: "18 Agustus 2026" },
            { muridId: 24, tanggal: "18 Agustus 2026" },
            { muridId: 25, tanggal: "19 Agustus 2026" },
            { muridId: 26, tanggal: "19 Agustus 2026" },
            { muridId: 27, tanggal: "20 Agustus 2026" },
            { muridId: 28, tanggal: "20 Agustus 2026" },
            { muridId: 29, tanggal: "21 Agustus 2026" },
            { muridId: 30, tanggal: "21 Agustus 2026" },
            { muridId: 31, tanggal: "22 Agustus 2026" },
            { muridId: 32, tanggal: "22 Agustus 2026" },
            { muridId: 1, tanggal: "22 Agustus 2026" },
            { muridId: 2, tanggal: "23 Agustus 2026" },
            { muridId: 3, tanggal: "23 Agustus 2026" },
            { muridId: 4, tanggal: "24 Agustus 2026" },
            { muridId: 5, tanggal: "24 Agustus 2026" },
            { muridId: 6, tanggal: "25 Agustus 2026" },
            { muridId: 7, tanggal: "25 Agustus 2026" },
            { muridId: 8, tanggal: "26 Agustus 2026" },
            { muridId: 9, tanggal: "26 Agustus 2026" },
            { muridId: 10, tanggal: "27 Agustus 2026" },
            { muridId: 11, tanggal: "27 Agustus 2026" },
            { muridId: 12, tanggal: "27 Agustus 2026" },
            { muridId: 13, tanggal: "28 Agustus 2026" },
            { muridId: 14, tanggal: "28 Agustus 2026" },
            { muridId: 15, tanggal: "29 Agustus 2026" },
            { muridId: 16, tanggal: "29 Agustus 2026" },
            { muridId: 17, tanggal: "30 Agustus 2026" },
            { muridId: 18, tanggal: "30 Agustus 2026" },
            { muridId: 19, tanggal: "31 Agustus 2026" },
            { muridId: 20, tanggal: "31 Agustus 2026" },
          ],
        },
      ],
      dataMurid: [
        { id: 1, nama: "Adam Saputra", nilai: [83, 79, 83, 79] },
        { id: 2, nama: "Andrew Toby", nilai: [91, 87, 91, 87] },
        { id: 3, nama: "Arfan Dwitara", nilai: [99, 95, 99, 90] },
        { id: 4, nama: "Eka Wulandari", nilai: [86, 82, 81, 77] },
        { id: 5, nama: "Gibran Rakabumi", nilai: [94, 85, 89, 85] },
        { id: 6, nama: "Ahmad Firmansyah", nilai: [97, 93, 97, 93] },
        { id: 7, nama: "Bagas Wulandari", nilai: [84, 80, 84, 80] },
        { id: 8, nama: "Bimo Ramadhan", nilai: [92, 88, 92, 83] },
        { id: 9, nama: "Candra Anggraini", nilai: [100, 96, 95, 91] },
        { id: 10, nama: "Daffa Safitri", nilai: [87, 78, 82, 78] },
        { id: 11, nama: "Dea Santoso", nilai: [90, 85, 89, 85] },
        { id: 12, nama: "Denny Syahputra", nilai: [97, 93, 97, 93] },
        { id: 13, nama: "Fajar Lestari", nilai: [84, 80, 84, 75] },
        { id: 14, nama: "Galih Permata", nilai: [92, 88, 87, 83] },
        { id: 15, nama: "Hendra Wicaksono", nilai: [100, 91, 95, 91] },
        { id: 16, nama: "Irfan Malik", nilai: [82, 78, 82, 78] },
        { id: 17, nama: "Jihan Hardiman", nilai: [90, 86, 90, 86] },
        { id: 18, nama: "Karim Dwitara", nilai: [98, 94, 98, 89] },
        { id: 19, nama: "Lukman Nuraini", nilai: [85, 81, 80, 76] },
        { id: 20, nama: "Mahler Hakim", nilai: [93, 84, 88, 84] },
        { id: 21, nama: "Nanda Hidayat", nilai: [96, 92, 96, 92] },
        { id: 22, nama: "Oki Wijaya", nilai: [83, 79, 83, 79] },
        { id: 23, nama: "Putra Halim", nilai: [91, 87, 91, 82] },
        { id: 24, nama: "Radit Fauzi", nilai: [99, 95, 94, 90] },
        { id: 25, nama: "Satria Kusuma", nilai: [86, 77, 81, 77] },
        { id: 26, nama: "Taufik Yuliana", nilai: [89, 85, 89, 85] },
        { id: 27, nama: "Umar Shara", nilai: [97, 93, 97, 93] },
        { id: 28, nama: "Wahyu Wibowo", nilai: [84, 80, 84, 75] },
        { id: 29, nama: "Yoga Toby", nilai: [92, 88, 87, 83] },
        { id: 30, nama: "Zaki Anggara", nilai: [100, 91, 95, 91] },
        { id: 31, nama: "Ardi Dewi", nilai: [82, 78, 82, 78] },
        { id: 32, nama: "Cahya Maulana", nilai: [90, 86, 90, 86] },
      ],
      pengumuman: [
        {
          id: 1,
          nama: "Ujian Akhir Semester",
          description: "Akan dilaksanakan pada tanggal 10 October 2026",
          date: "29 September 2026",
        },
        {
          id: 2,
          nama: "Pengumpulan Tugas",
          description: "Kumpulkan Tugas sebelum 1 September 2026",
          date: "27 September 2026",
        },
        {
          id: 3,
          nama: "Materi Baru: Teks Pidato Persuasif",
          description:
            "Materi bab pidato persuasif sudah tersedia. Silakan unduh di halaman materi.",
          date: "22 September 2026",
        },
      ],
    },
    {
      id: 2,
      kelas: "XI DKV A",
      totalMurid: 28,
      materi: [
        {
          id: 1,
          title: "Teks Deskripsi dalam Desain Visual",
          desc: "Menerapkan struktur teks deskripsi pada caption dan keterangan karya visual: objek, atribut, dan suasana. Materi disertai contoh caption poster dan produk kemasan.",
          attachedFiles: ["/materi/deskripsi-visual.pdf", "/materi/contoh-caption-poster.jpg"],
        },
        {
          id: 2,
          title: "Copywriting untuk Poster & Kemasan",
          desc: "Menyusun judul, subjudul, dan kalimat ajakan singkat yang efektif untuk media cetak, dengan perhatian pada daya tarik visual dan batasan karakter.",
          attachedFiles: ["/materi/copywriting-poster.pdf", "https://kemdikbud.go.id/copywriting"],
        },
        {
          id: 3,
          title: "Teks Laporan Hasil Proyek",
          desc: "Struktur laporan proyek desain: latar belakang, tujuan, proses pembuatan, hasil, dan kesimpulan, beserta cara menyusun dokumentasi visual yang runtut.",
          attachedFiles: ["/materi/laporan-proyek.pdf"],
        },
        {
          id: 4,
          title: "Etika dan Bahasa dalam Publikasi",
          desc: "Penggunaan bahasa Indonesia yang baku pada poster, katalog, dan media sosial, termasuk ejaan, kapitalisasi, serta menghindari bahasa yang menyinggung.",
          attachedFiles: ["/materi/etika-bahasa.pdf", "https://kbbi.kemdikbud.go.id/"],
        },
      ],
      tugas: [
        {
          id: 1,
          name: "Caption Poster",
          ditugaskan: "20 Agustus 2026",
          deadline: "10 September 2026",
          deskripsi:
            "Buat tiga variasi caption untuk poster kegiatan sekolah. Setiap caption harus memiliki panjang maksimal 60 karakter, menggunakan kalimat ajakan, dan memuat satu kata kunci yang relevan. Jelaskan alasan pemilihan kata pada setiap variasi. Kumpulkan dalam format dokumen (.pdf), minimal 150 kata.",
          completed: false,
          muridSelesai: 14,
          pengumpulan: [
            { muridId: 4, tanggal: "20 Agustus 2026" },
            { muridId: 5, tanggal: "21 Agustus 2026" },
            { muridId: 6, tanggal: "23 Agustus 2026" },
            { muridId: 7, tanggal: "24 Agustus 2026" },
            { muridId: 8, tanggal: "26 Agustus 2026" },
            { muridId: 9, tanggal: "27 Agustus 2026" },
            { muridId: 10, tanggal: "29 Agustus 2026" },
            { muridId: 11, tanggal: "30 Agustus 2026" },
            { muridId: 12, tanggal: "1 September 2026" },
            { muridId: 13, tanggal: "2 September 2026" },
            { muridId: 14, tanggal: "4 September 2026" },
            { muridId: 15, tanggal: "5 September 2026" },
            { muridId: 16, tanggal: "7 September 2026" },
            { muridId: 17, tanggal: "8 September 2026" },
          ],
        },
        {
          id: 2,
          name: "Analisis Unsur Intrinsik Cerpen",
          ditugaskan: "22 Juli 2026",
          deadline: "12 Agustus 2026",
          deskripsi:
            "Baca satu cerpen yang ditentukan guru, lalu identifikasi kelima unsur intrinsik - tokoh, penokohan, latar, konflik, dan amanat. Untuk setiap unsur, sertakan kutipan kalimat dari cerpen sebagai bukti dan satu kalimat penjelasan. Tulis analisis dalam bentuk paragraf, bukan poin-poin, minimal 300 kata.",
          completed: true,
          muridSelesai: 28,
          pengumpulan: [
            { muridId: 11, tanggal: "22 Juli 2026" },
            { muridId: 12, tanggal: "22 Juli 2026" },
            { muridId: 13, tanggal: "23 Juli 2026" },
            { muridId: 14, tanggal: "24 Juli 2026" },
            { muridId: 15, tanggal: "25 Juli 2026" },
            { muridId: 16, tanggal: "25 Juli 2026" },
            { muridId: 17, tanggal: "26 Juli 2026" },
            { muridId: 18, tanggal: "27 Juli 2026" },
            { muridId: 19, tanggal: "28 Juli 2026" },
            { muridId: 20, tanggal: "28 Juli 2026" },
            { muridId: 21, tanggal: "29 Juli 2026" },
            { muridId: 22, tanggal: "30 Juli 2026" },
            { muridId: 23, tanggal: "31 Juli 2026" },
            { muridId: 24, tanggal: "31 Juli 2026" },
            { muridId: 25, tanggal: "1 Agustus 2026" },
            { muridId: 26, tanggal: "2 Agustus 2026" },
            { muridId: 27, tanggal: "3 Agustus 2026" },
            { muridId: 28, tanggal: "3 Agustus 2026" },
            { muridId: 1, tanggal: "4 Agustus 2026" },
            { muridId: 2, tanggal: "5 Agustus 2026" },
            { muridId: 3, tanggal: "6 Agustus 2026" },
            { muridId: 4, tanggal: "6 Agustus 2026" },
            { muridId: 5, tanggal: "7 Agustus 2026" },
            { muridId: 6, tanggal: "8 Agustus 2026" },
            { muridId: 7, tanggal: "9 Agustus 2026" },
            { muridId: 8, tanggal: "9 Agustus 2026" },
            { muridId: 9, tanggal: "10 Agustus 2026" },
            { muridId: 10, tanggal: "11 Agustus 2026" },
          ],
        },
        {
          id: 3,
          name: "Copywriting Poster",
          ditugaskan: "20 Agustus 2026",
          deadline: "24 Agustus 2026",
          deskripsi:
            "Tulis naskah copy untuk poster kegiatan sekolah. Naskah terdiri dari headline, sub-headline, dan body copy yang memuat ajakan bertindak. Gunakan gaya bahasa yang jelas dan jangan membuat klaim yang tidak terbukti. Kumpulkan dalam format dokumen (.pdf), minimal 250 kata.",
          completed: true,
          muridSelesai: 22,
          pengumpulan: [
            { muridId: 18, tanggal: "20 Agustus 2026" },
            { muridId: 19, tanggal: "20 Agustus 2026" },
            { muridId: 20, tanggal: "20 Agustus 2026" },
            { muridId: 21, tanggal: "20 Agustus 2026" },
            { muridId: 22, tanggal: "20 Agustus 2026" },
            { muridId: 23, tanggal: "20 Agustus 2026" },
            { muridId: 24, tanggal: "21 Agustus 2026" },
            { muridId: 25, tanggal: "21 Agustus 2026" },
            { muridId: 26, tanggal: "21 Agustus 2026" },
            { muridId: 27, tanggal: "21 Agustus 2026" },
            { muridId: 28, tanggal: "21 Agustus 2026" },
            { muridId: 1, tanggal: "22 Agustus 2026" },
            { muridId: 2, tanggal: "22 Agustus 2026" },
            { muridId: 3, tanggal: "22 Agustus 2026" },
            { muridId: 4, tanggal: "22 Agustus 2026" },
            { muridId: 5, tanggal: "22 Agustus 2026" },
            { muridId: 6, tanggal: "22 Agustus 2026" },
            { muridId: 7, tanggal: "23 Agustus 2026" },
            { muridId: 8, tanggal: "23 Agustus 2026" },
            { muridId: 9, tanggal: "23 Agustus 2026" },
            { muridId: 10, tanggal: "23 Agustus 2026" },
            { muridId: 11, tanggal: "23 Agustus 2026" },
          ],
        },
        {
          id: 4,
          name: "Laporan Proyek Desain",
          ditugaskan: "18 Agustus 2026",
          deadline: "1 September 2026",
          deskripsi:
            "Tulis laporan hasil proyek desain yang kamu kerjakan. Laporan memuat latar belakang, tujuan, proses pengerjaan yang dilakukan, hasil akhir, dan evaluasi diri. Sertakan dokumentasi berupa foto atau tangkapan layar dari proses pengerjaan. Minimal 400 kata.",
          completed: true,
          muridSelesai: 26,
          pengumpulan: [
            { muridId: 25, tanggal: "18 Agustus 2026" },
            { muridId: 26, tanggal: "18 Agustus 2026" },
            { muridId: 27, tanggal: "19 Agustus 2026" },
            { muridId: 28, tanggal: "19 Agustus 2026" },
            { muridId: 1, tanggal: "20 Agustus 2026" },
            { muridId: 2, tanggal: "20 Agustus 2026" },
            { muridId: 3, tanggal: "21 Agustus 2026" },
            { muridId: 4, tanggal: "21 Agustus 2026" },
            { muridId: 5, tanggal: "22 Agustus 2026" },
            { muridId: 6, tanggal: "22 Agustus 2026" },
            { muridId: 7, tanggal: "23 Agustus 2026" },
            { muridId: 8, tanggal: "23 Agustus 2026" },
            { muridId: 9, tanggal: "24 Agustus 2026" },
            { muridId: 10, tanggal: "25 Agustus 2026" },
            { muridId: 11, tanggal: "25 Agustus 2026" },
            { muridId: 12, tanggal: "26 Agustus 2026" },
            { muridId: 13, tanggal: "26 Agustus 2026" },
            { muridId: 14, tanggal: "27 Agustus 2026" },
            { muridId: 15, tanggal: "27 Agustus 2026" },
            { muridId: 16, tanggal: "28 Agustus 2026" },
            { muridId: 17, tanggal: "28 Agustus 2026" },
            { muridId: 18, tanggal: "29 Agustus 2026" },
            { muridId: 19, tanggal: "29 Agustus 2026" },
            { muridId: 20, tanggal: "30 Agustus 2026" },
            { muridId: 21, tanggal: "30 Agustus 2026" },
            { muridId: 22, tanggal: "31 Agustus 2026" },
          ],
        },
      ],
      dataMurid: [
        { id: 1, nama: "Adam Wulandari", nilai: [78, 74, 78, 74] },
        { id: 2, nama: "Andrew Ramadhan", nilai: [86, 82, 86, 82] },
        { id: 3, nama: "Arfan Anggraini", nilai: [94, 90, 94, 85] },
        { id: 4, nama: "Eka Safitri", nilai: [79, 75, 74, 70] },
        { id: 5, nama: "Gibran Santoso", nilai: [87, 78, 82, 78] },
        { id: 6, nama: "Ahmad Syahputra", nilai: [90, 86, 90, 86] },
        { id: 7, nama: "Bagas Lestari", nilai: [98, 94, 98, 94] },
        { id: 8, nama: "Bimo Permata", nilai: [83, 79, 83, 74] },
        { id: 9, nama: "Candra Wicaksono", nilai: [91, 87, 86, 82] },
        { id: 10, nama: "Daffa Malik", nilai: [98, 90, 94, 90] },
        { id: 11, nama: "Dea Hardiman", nilai: [79, 75, 79, 75] },
        { id: 12, nama: "Denny Dwitara", nilai: [87, 83, 87, 83] },
        { id: 13, nama: "Fajar Nuraini", nilai: [95, 91, 95, 86] },
        { id: 14, nama: "Galih Hakim", nilai: [80, 76, 75, 71] },
        { id: 15, nama: "Hendra Hidayat", nilai: [88, 79, 83, 79] },
        { id: 16, nama: "Irfan Wijaya", nilai: [91, 87, 91, 87] },
        { id: 17, nama: "Jihan Halim", nilai: [76, 72, 76, 72] },
        { id: 18, nama: "Karim Fauzi", nilai: [85, 81, 85, 76] },
        { id: 19, nama: "Lukman Kusuma", nilai: [93, 89, 88, 84] },
        { id: 20, nama: "Mahler Yuliana", nilai: [99, 92, 96, 92] },
        { id: 21, nama: "Nanda Shara", nilai: [81, 77, 81, 77] },
        { id: 22, nama: "Oki Wibowo", nilai: [89, 85, 89, 85] },
        { id: 23, nama: "Putra Toby", nilai: [97, 93, 97, 88] },
        { id: 24, nama: "Radit Anggara", nilai: [82, 78, 77, 73] },
        { id: 25, nama: "Satria Dewi", nilai: [90, 81, 85, 81] },
        { id: 26, nama: "Taufik Maulana", nilai: [93, 89, 93, 89] },
        { id: 27, nama: "Umar Ningrum", nilai: [78, 74, 78, 74] },
        { id: 28, nama: "Wahyu Setiawan", nilai: [86, 82, 86, 77] },
      ],
      pengumuman: [
        {
          id: 1,
          nama: "Ujian Akhir Semester",
          description: "Akan dilaksanakan pada tanggal 10 Oktober 2026",
          date: "29 September 2026",
        },
        {
          id: 2,
          nama: "Brief Proyek Poster",
          description:
            "Brief proyek poster untuk XI DKV A sudah dibagikan. Batas pengumpulan 1 Oktober 2026.",
          date: "26 September 2026",
        },
        {
          id: 3,
          nama: "Materi Copywriting",
          description: "Materi bab copywriting untuk media cetak sudah tersedia di halaman materi.",
          date: "20 September 2026",
        },
      ],
    },
    {
      id: 3,
      kelas: "XI RPL C",
      totalMurid: 30,
      materi: [
        {
          id: 1,
          title: "Belajar Teks Eksposisi",
          desc: "Mengenal teks eksposisi sebagai teks yang bertujuan menjelaskan suatu peristiwa atau gagasan secara sistematis, beserta tesis, rangkaian argumen, dan penegasan ulang.",
          attachedFiles: ["/materi/eksposisi-modul.pdf", "https://kemdikbud.go.id/teks-eksposisi"],
        },
        {
          id: 2,
          title: "Unsur Intrinsik Cerpen",
          desc: "Mempelajari lima unsur intrinsik cerpen — tokoh, penokohan, latar, konflik, dan amanat — beserta cara mengidentifikasi setiap unsur pada kutipan cerita pendek.",
          attachedFiles: ["/materi/cerpen-unsur.pdf", "/materi/cerpen-kisah-di-sekolah.docx"],
        },
        {
          id: 3,
          title: "Teks Pidato Persuasif",
          desc: "Struktur pembuka, isi, dan penutup teks pidato persuasif, disertai teknik kebahasaan persuasif dan cara menyusun data yang kuat untuk membahas isu lingkungan.",
          attachedFiles: ["https://id.wikipedia.org/wiki/Pidato_persuasif"],
        },
        {
          id: 4,
          title: "Membuat Resensi Buku",
          desc: "Panduan menulis resensi: identitas buku, sinopsis, kelebihan, dan kekurangan, serta cara memberi rekomendasi yang jujur berdasarkan pembacaan utuh.",
          attachedFiles: ["/materi/resensi-panduan.pdf", "/materi/contoh-resensi.pdf"],
        },
      ],
      tugas: [
        {
          id: 1,
          name: "Menulis Teks Eksposisi",
          ditugaskan: "20 Agustus 2026",
          deadline: "10 September 2026",
          deskripsi:
            "Susun sebuah teks eksposisi dengan tema bebas yang berkaitan dengan isu pendidikan di sekitar sekolah. Teks harus memuat tesis di paragraf pembuka, rangkaian argumen yang tersusun logis, dan penegasan ulang di paragraf penutup. Gunakan kalimat efektif dan kutipan dari sumber yang kredibel, minimal tiga sumber berbeda. Kumpulkan dalam format dokumen (.pdf atau .docx), minimal 350 kata.",
          completed: false,
          muridSelesai: 19,
          pengumpulan: [
            { muridId: 7, tanggal: "20 Agustus 2026" },
            { muridId: 8, tanggal: "21 Agustus 2026" },
            { muridId: 9, tanggal: "22 Agustus 2026" },
            { muridId: 10, tanggal: "23 Agustus 2026" },
            { muridId: 11, tanggal: "24 Agustus 2026" },
            { muridId: 12, tanggal: "25 Agustus 2026" },
            { muridId: 13, tanggal: "26 Agustus 2026" },
            { muridId: 14, tanggal: "27 Agustus 2026" },
            { muridId: 15, tanggal: "28 Agustus 2026" },
            { muridId: 16, tanggal: "29 Agustus 2026" },
            { muridId: 17, tanggal: "31 Agustus 2026" },
            { muridId: 18, tanggal: "1 September 2026" },
            { muridId: 19, tanggal: "2 September 2026" },
            { muridId: 20, tanggal: "3 September 2026" },
            { muridId: 21, tanggal: "4 September 2026" },
            { muridId: 22, tanggal: "5 September 2026" },
            { muridId: 23, tanggal: "6 September 2026" },
            { muridId: 24, tanggal: "7 September 2026" },
            { muridId: 25, tanggal: "8 September 2026" },
          ],
        },
        {
          id: 2,
          name: "Analisis Unsur Intrinsik Cerpen",
          ditugaskan: "22 Juli 2026",
          deadline: "12 Agustus 2026",
          deskripsi:
            "Baca satu cerpen yang ditentukan guru, lalu identifikasi kelima unsur intrinsik - tokoh, penokohan, latar, konflik, dan amanat. Untuk setiap unsur, sertakan kutipan kalimat dari cerpen sebagai bukti dan satu kalimat penjelasan. Tulis analisis dalam bentuk paragraf, bukan poin-poin, minimal 300 kata.",
          completed: true,
          muridSelesai: 30,
          pengumpulan: [
            { muridId: 14, tanggal: "22 Juli 2026" },
            { muridId: 15, tanggal: "22 Juli 2026" },
            { muridId: 16, tanggal: "23 Juli 2026" },
            { muridId: 17, tanggal: "24 Juli 2026" },
            { muridId: 18, tanggal: "24 Juli 2026" },
            { muridId: 19, tanggal: "25 Juli 2026" },
            { muridId: 20, tanggal: "26 Juli 2026" },
            { muridId: 21, tanggal: "26 Juli 2026" },
            { muridId: 22, tanggal: "27 Juli 2026" },
            { muridId: 23, tanggal: "28 Juli 2026" },
            { muridId: 24, tanggal: "29 Juli 2026" },
            { muridId: 25, tanggal: "29 Juli 2026" },
            { muridId: 26, tanggal: "30 Juli 2026" },
            { muridId: 27, tanggal: "31 Juli 2026" },
            { muridId: 28, tanggal: "31 Juli 2026" },
            { muridId: 29, tanggal: "1 Agustus 2026" },
            { muridId: 30, tanggal: "2 Agustus 2026" },
            { muridId: 1, tanggal: "2 Agustus 2026" },
            { muridId: 2, tanggal: "3 Agustus 2026" },
            { muridId: 3, tanggal: "4 Agustus 2026" },
            { muridId: 4, tanggal: "5 Agustus 2026" },
            { muridId: 5, tanggal: "5 Agustus 2026" },
            { muridId: 6, tanggal: "6 Agustus 2026" },
            { muridId: 7, tanggal: "7 Agustus 2026" },
            { muridId: 8, tanggal: "7 Agustus 2026" },
            { muridId: 9, tanggal: "8 Agustus 2026" },
            { muridId: 10, tanggal: "9 Agustus 2026" },
            { muridId: 11, tanggal: "9 Agustus 2026" },
            { muridId: 12, tanggal: "10 Agustus 2026" },
            { muridId: 13, tanggal: "11 Agustus 2026" },
          ],
        },
        {
          id: 3,
          name: "Membuat Teks Pidato Persuasif",
          ditugaskan: "20 Agustus 2026",
          deadline: "10 September 2026",
          deskripsi:
            "Siswa membuat teks pidato persuasif dengan tema bebas yang berkaitan dengan isu lingkungan di sekitar sekolah. Pidato harus memuat struktur pembuka, isi, dan penutup, serta minimal tiga argumen yang didukung data atau fakta. Kumpulkan dalam format dokumen (.pdf atau .docx), minimal 400 kata.",
          completed: true,
          muridSelesai: 25,
          pengumpulan: [
            { muridId: 21, tanggal: "20 Agustus 2026" },
            { muridId: 22, tanggal: "20 Agustus 2026" },
            { muridId: 23, tanggal: "21 Agustus 2026" },
            { muridId: 24, tanggal: "22 Agustus 2026" },
            { muridId: 25, tanggal: "23 Agustus 2026" },
            { muridId: 26, tanggal: "24 Agustus 2026" },
            { muridId: 27, tanggal: "25 Agustus 2026" },
            { muridId: 28, tanggal: "25 Agustus 2026" },
            { muridId: 29, tanggal: "26 Agustus 2026" },
            { muridId: 30, tanggal: "27 Agustus 2026" },
            { muridId: 1, tanggal: "28 Agustus 2026" },
            { muridId: 2, tanggal: "29 Agustus 2026" },
            { muridId: 3, tanggal: "30 Agustus 2026" },
            { muridId: 4, tanggal: "30 Agustus 2026" },
            { muridId: 5, tanggal: "31 Agustus 2026" },
            { muridId: 6, tanggal: "1 September 2026" },
            { muridId: 7, tanggal: "2 September 2026" },
            { muridId: 8, tanggal: "3 September 2026" },
            { muridId: 9, tanggal: "4 September 2026" },
            { muridId: 10, tanggal: "4 September 2026" },
            { muridId: 11, tanggal: "5 September 2026" },
            { muridId: 12, tanggal: "6 September 2026" },
            { muridId: 13, tanggal: "7 September 2026" },
            { muridId: 14, tanggal: "8 September 2026" },
            { muridId: 15, tanggal: "9 September 2026" },
          ],
        },
        {
          id: 4,
          name: "Membuat Resensi Buku",
          ditugaskan: "18 Agustus 2026",
          deadline: "1 September 2026",
          deskripsi:
            "Tulis resensi terhadap buku fiksi pilihanmu. Resensi wajib memuat identitas buku, sinopsis, penilaian atas isi dan kegunaan, serta komentar evaluatif terhadap kebahasaan dan penerbit. Sertakan minimal tiga kutipan dari buku yang kamu kutip beserta nomor halaman. Minimal 400 kata.",
          completed: true,
          muridSelesai: 29,
          pengumpulan: [
            { muridId: 28, tanggal: "18 Agustus 2026" },
            { muridId: 29, tanggal: "18 Agustus 2026" },
            { muridId: 30, tanggal: "18 Agustus 2026" },
            { muridId: 1, tanggal: "19 Agustus 2026" },
            { muridId: 2, tanggal: "19 Agustus 2026" },
            { muridId: 3, tanggal: "20 Agustus 2026" },
            { muridId: 4, tanggal: "20 Agustus 2026" },
            { muridId: 5, tanggal: "21 Agustus 2026" },
            { muridId: 6, tanggal: "21 Agustus 2026" },
            { muridId: 7, tanggal: "22 Agustus 2026" },
            { muridId: 8, tanggal: "22 Agustus 2026" },
            { muridId: 9, tanggal: "23 Agustus 2026" },
            { muridId: 10, tanggal: "23 Agustus 2026" },
            { muridId: 11, tanggal: "24 Agustus 2026" },
            { muridId: 12, tanggal: "24 Agustus 2026" },
            { muridId: 13, tanggal: "25 Agustus 2026" },
            { muridId: 14, tanggal: "25 Agustus 2026" },
            { muridId: 15, tanggal: "26 Agustus 2026" },
            { muridId: 16, tanggal: "26 Agustus 2026" },
            { muridId: 17, tanggal: "27 Agustus 2026" },
            { muridId: 18, tanggal: "27 Agustus 2026" },
            { muridId: 19, tanggal: "28 Agustus 2026" },
            { muridId: 20, tanggal: "28 Agustus 2026" },
            { muridId: 21, tanggal: "29 Agustus 2026" },
            { muridId: 22, tanggal: "29 Agustus 2026" },
            { muridId: 23, tanggal: "30 Agustus 2026" },
            { muridId: 24, tanggal: "30 Agustus 2026" },
            { muridId: 25, tanggal: "31 Agustus 2026" },
            { muridId: 26, tanggal: "31 Agustus 2026" },
          ],
        },
      ],
      dataMurid: [
        { id: 1, nama: "Adam Lestari", nilai: [87, 83, 87, 83] },
        { id: 2, nama: "Andrew Permata", nilai: [95, 91, 95, 91] },
        { id: 3, nama: "Arfan Wicaksono", nilai: [100, 99, 100, 94] },
        { id: 4, nama: "Eka Malik", nilai: [88, 84, 83, 79] },
        { id: 5, nama: "Gibran Hardiman", nilai: [96, 87, 91, 87] },
        { id: 6, nama: "Ahmad Dwitara", nilai: [99, 95, 99, 95] },
        { id: 7, nama: "Bagas Nuraini", nilai: [84, 80, 84, 80] },
        { id: 8, nama: "Bimo Hakim", nilai: [92, 88, 92, 83] },
        { id: 9, nama: "Candra Hidayat", nilai: [100, 96, 95, 91] },
        { id: 10, nama: "Daffa Wijaya", nilai: [85, 76, 80, 76] },
        { id: 11, nama: "Dea Halim", nilai: [88, 84, 88, 84] },
        { id: 12, nama: "Denny Fauzi", nilai: [96, 92, 96, 92] },
        { id: 13, nama: "Fajar Kusuma", nilai: [100, 100, 100, 95] },
        { id: 14, nama: "Galih Yuliana", nilai: [89, 85, 84, 80] },
        { id: 15, nama: "Hendra Shara", nilai: [97, 88, 92, 88] },
        { id: 16, nama: "Irfan Wibowo", nilai: [100, 96, 100, 96] },
        { id: 17, nama: "Jihan Toby", nilai: [85, 81, 85, 81] },
        { id: 18, nama: "Karim Anggara", nilai: [93, 89, 92, 83] },
        { id: 19, nama: "Lukman Dewi", nilai: [100, 96, 95, 91] },
        { id: 20, nama: "Mahler Maulana", nilai: [85, 76, 80, 76] },
        { id: 21, nama: "Nanda Ningrum", nilai: [88, 84, 88, 84] },
        { id: 22, nama: "Oki Setiawan", nilai: [96, 92, 96, 92] },
        { id: 23, nama: "Putra Rakabumi", nilai: [81, 77, 81, 72] },
        { id: 24, nama: "Radit Puspita", nilai: [89, 85, 84, 80] },
        { id: 25, nama: "Satria Prasetyo", nilai: [97, 88, 92, 88] },
        { id: 26, nama: "Taufik Nugroho", nilai: [100, 96, 100, 96] },
        { id: 27, nama: "Umar Pratama", nilai: [85, 81, 85, 81] },
        { id: 28, nama: "Wahyu Saputra", nilai: [93, 89, 93, 84] },
        { id: 29, nama: "Yoga Amelia", nilai: [100, 98, 96, 92] },
        { id: 30, nama: "Zaki Jamaludin", nilai: [86, 77, 81, 77] },
      ],
      pengumuman: [
        {
          id: 1,
          nama: "Ujian Akhir Semester",
          description: "Akan dilaksanakan pada tanggal 10 Oktober 2026",
          date: "29 September 2026",
        },
        {
          id: 2,
          nama: "Jadwal remedial",
          description:
            "Remedial bagi siswa dengan nilai di bawah KKM 80 dilaksanakan Sabtu, 05.00 WIB.",
          date: "25 September 2026",
        },
        {
          id: 3,
          nama: "Pengumpulan Tugas",
          description: "Kumpulkan tugas sebelum 1 September 2026",
          date: "27 September 2026",
        },
      ],
    },
  ],
};

export type GuruClass = (typeof dummyGuruData.dataKelas)[number];

/** Look up one class by id — routes are `/teacher/home/[id]`. */
export function findClass(id: number): GuruClass | undefined {
  return dummyGuruData.dataKelas.find((c) => c.id === id);
}
