/**
 * Demo persona + helpers for the frontend-only admin pages. The real admin
 * session replaces these when the backend pass wires Supabase/role guards.
 *
 * Deliberately NOT "use client" — it is plain static data, so server
 * components can import it too (e.g. to redirect /teacher/home -> /1).
 */

export const dummyGuruData = {
  name: "Bu Dewi Lestari",
  email: "admin@grafidu.sch.id",
  mapel: "Bahasa Indonesia",
  rataRataKelas: 87.1,
  kkm: 80,
  dataKelas: [
    {
      id: 1,
      kelas: "XI RPL B",
      totalMurid: 32,
      materi: [
        {
          id: 1,
          title: "Belajar Teks Eksposisi",
          desc: "Mengenal teks eksposisi sebagai teks yang bertujuan menjelaskan suatu peristiwa atau gagasan secara sistematis. Materi ini membahas tesis, rangkaian argumen, dan penegasan ulang, disertai contoh teks tentang isu lingkungan di sekitar sekolah.",
          attachedFiles: ["/materi/eksposisi-modul.pdf", "https://kemdikbud.go.id/teks-eksposisi"],
        },
        {
          id: 2,
          title: "Unsur Intrinsik Cerpen",
          desc: "Mempelajari lima unsur intrinsik cerpen — tokoh, penokohan, latar, konflik, dan amanat — beserta cara mengidentifikasi setiap unsur pada kutipan cerita pendek.",
          attachedFiles: ["/materi/cerpen-unsur.pdf", "/materi/cerpen-kisah-di-sekolah.docx"],
        },
        {
          id: 3,
          title: "Teks Pidato Persuasif",
          desc: "Struktur pembuka, isi, dan penutup teks pidato persuasif, disertai teknik kebahasaan persuasif dan cara menyusun data yang kuat untuk membahas isu lingkungan.",
          attachedFiles: ["https://id.wikipedia.org/wiki/Pidato_persuasif"],
        },
        {
          id: 4,
          title: "Membuat Resensi Buku",
          desc: "Panduan menulis resensi: identitas buku, sinopsis, kelebihan, dan kekurangan, serta cara memberi rekomendasi yang jujur berdasarkan pembacaan utuh.",
          attachedFiles: ["/materi/resensi-panduan.pdf", "/materi/contoh-resensi.pdf"],
        },
      ],
      tugas: [
        {
          id: 1,
          name: "Menulis Teks Eksposisi",
          deadline: "10 September 2026",
          completed: false,
          muridSelesai: 16,
        },
        {
          id: 2,
          name: "Analisis Unsur Intrinsik Cerpen",
          deadline: "12 Agustus 2026",
          completed: true,
          muridSelesai: 32,
        },
        {
          id: 3,
          name: "Membuat Teks Pidato Persuasif",
          deadline: "24 Agustus 2026",
          completed: true,
          muridSelesai: 27,
        },
        {
          id: 4,
          name: "Membuat Resensi Buku",
          deadline: "1 September 2026",
          completed: true,
          muridSelesai: 31,
        },
      ],
      dataMurid: [
        { id: 1, nama: "Prabima", nilai: [83, 79, 83, 79] },
        { id: 2, nama: "Farid Diva", nilai: [91, 87, 91, 87] },
        { id: 3, nama: "Gibran Rakabumi", nilai: [99, 95, 99, 90] },
        { id: 4, nama: "Joko Prabumi", nilai: [86, 82, 81, 77] },
        { id: 5, nama: "Jessie Cooper", nilai: [94, 85, 89, 85] },
        { id: 6, nama: "Ahmad Fauzi", nilai: [97, 93, 97, 93] },
        { id: 7, nama: "Bunga Lestari", nilai: [84, 80, 84, 80] },
        { id: 8, nama: "Citra Amelia", nilai: [92, 88, 92, 83] },
        { id: 9, nama: "Dimas Anggara", nilai: [100, 96, 95, 91] },
        { id: 10, nama: "Elsa Nuraini", nilai: [87, 78, 82, 78] },
        { id: 11, nama: "Fajar Ramadhan", nilai: [90, 85, 89, 85] },
        { id: 12, nama: "Gita Puspita", nilai: [97, 93, 97, 93] },
        { id: 13, nama: "Hendra Kusuma", nilai: [84, 80, 84, 75] },
        { id: 14, nama: "Indah Permata", nilai: [92, 88, 87, 83] },
        { id: 15, nama: "Jamaludin", nilai: [100, 91, 95, 91] },
        { id: 16, nama: "Kirana Dewi", nilai: [82, 78, 82, 78] },
        { id: 17, nama: "Lukman Hakim", nilai: [90, 86, 90, 86] },
        { id: 18, nama: "Maya Anggraini", nilai: [98, 94, 98, 89] },
        { id: 19, nama: "Nanda Prasetyo", nilai: [85, 81, 80, 76] },
        { id: 20, nama: "Olivia Yuliana", nilai: [93, 84, 88, 84] },
        { id: 21, nama: "Panji Wicaksono", nilai: [96, 92, 96, 92] },
        { id: 22, nama: "Ratna Kumala", nilai: [83, 79, 83, 79] },
        { id: 23, nama: "Rizky Maulana", nilai: [91, 87, 91, 82] },
        { id: 24, nama: "Salsabila Hakim", nilai: [99, 95, 94, 90] },
        { id: 25, nama: "Taufik Hidayat", nilai: [86, 77, 81, 77] },
        { id: 26, nama: "Ulfa Safitri", nilai: [89, 85, 89, 85] },
        { id: 27, nama: "Wahyu Nugroho", nilai: [97, 93, 97, 93] },
        { id: 28, nama: "Yuni Shara", nilai: [84, 80, 84, 75] },
        { id: 29, nama: "Zakiuddin Malik", nilai: [92, 88, 87, 83] },
        { id: 30, nama: "Anisa Rahma", nilai: [100, 91, 95, 91] },
        { id: 31, nama: "Bayu Anggara", nilai: [82, 78, 82, 78] },
        { id: 32, nama: "Cahya Ningrum", nilai: [90, 86, 90, 86] },
      ],
      pengumuman: [
        {
          id: 1,
          nama: "Ujian Akhir Semester",
          description: "Akan dilaksanakan pada tanggal 10 October 2026",
          date: "29 September 2026",
        },
        {
          id: 2,
          nama: "Pengumpulan Tugas",
          description: "Kumpulkan Tugas sebelum 1 September 2026",
          date: "27 September 2026",
        },
        {
          id: 3,
          nama: "Materi Baru: Teks Pidato Persuasif",
          description:
            "Materi bab pidato persuasif sudah tersedia. Silakan unduh di halaman materi.",
          date: "22 September 2026",
        },
      ],
    },
    {
      id: 2,
      kelas: "XI DKV A",
      totalMurid: 28,
      materi: [
        {
          id: 1,
          title: "Teks Deskripsi dalam Desain Visual",
          desc: "Menerapkan struktur teks deskripsi pada caption dan keterangan karya visual: objek, atribut, dan suasana. Materi disertai contoh caption poster dan produk kemasan.",
          attachedFiles: ["/materi/deskripsi-visual.pdf", "/materi/contoh-caption-poster.jpg"],
        },
        {
          id: 2,
          title: "Copywriting untuk Poster & Kemasan",
          desc: "Menyusun judul, subjudul, dan kalimat ajakan singkat yang efektif untuk media cetak, dengan perhatian pada daya tarik visual dan batasan karakter.",
          attachedFiles: ["/materi/copywriting-poster.pdf", "https://kemdikbud.go.id/copywriting"],
        },
        {
          id: 3,
          title: "Teks Laporan Hasil Proyek",
          desc: "Struktur laporan proyek desain: latar belakang, tujuan, proses pembuatan, hasil, dan kesimpulan, beserta cara menyusun dokumentasi visual yang runtut.",
          attachedFiles: ["/materi/laporan-proyek.pdf"],
        },
        {
          id: 4,
          title: "Etika dan Bahasa dalam Publikasi",
          desc: "Penggunaan bahasa Indonesia yang baku pada poster, katalog, dan media sosial, termasuk ejaan, kapitalisasi, serta menghindari bahasa yang menyinggung.",
          attachedFiles: ["/materi/etika-bahasa.pdf", "https://kbbi.kemdikbud.go.id/"],
        },
      ],
      tugas: [
        {
          id: 1,
          name: "Caption Poster",
          deadline: "10 September 2026",
          completed: false,
          muridSelesai: 14,
        },
        {
          id: 2,
          name: "Analisis Unsur Intrinsik Cerpen",
          deadline: "12 Agustus 2026",
          completed: true,
          muridSelesai: 28,
        },
        {
          id: 3,
          name: "Copywriting Poster",
          deadline: "24 Agustus 2026",
          completed: true,
          muridSelesai: 22,
        },
        {
          id: 4,
          name: "Laporan Proyek Desain",
          deadline: "1 September 2026",
          completed: true,
          muridSelesai: 26,
        },
      ],
      dataMurid: [
        { id: 1, nama: "Alya Rahmawati", nilai: [78, 74, 78, 74] },
        { id: 2, nama: "Bagas Nugroho", nilai: [86, 82, 86, 82] },
        { id: 3, nama: "Citra Kirana", nilai: [94, 90, 94, 85] },
        { id: 4, nama: "Daffa Ramadhan", nilai: [79, 75, 74, 70] },
        { id: 5, nama: "Enggar Saputra", nilai: [87, 78, 82, 78] },
        { id: 6, nama: "Firda Aulia", nilai: [90, 86, 90, 86] },
        { id: 7, nama: "Gilang Permana", nilai: [98, 94, 98, 94] },
        { id: 8, nama: "Hanifa Khairunnisa", nilai: [83, 79, 83, 74] },
        { id: 9, nama: "Irfan Maulana", nilai: [91, 87, 86, 82] },
        { id: 10, nama: "Jihan Anindya", nilai: [98, 90, 94, 90] },
        { id: 11, nama: "Krisna Wicaya", nilai: [79, 75, 79, 75] },
        { id: 12, nama: "La Ode Saputra", nilai: [87, 83, 87, 83] },
        { id: 13, nama: "Maharani Sekar", nilai: [95, 91, 95, 86] },
        { id: 14, nama: "Nadia Puspasari", nilai: [80, 76, 75, 71] },
        { id: 15, nama: "Oktavia Rahma", nilai: [88, 79, 83, 79] },
        { id: 16, nama: "Pradnya Putra", nilai: [91, 87, 91, 87] },
        { id: 17, nama: "Qonita Zahra", nilai: [76, 72, 76, 72] },
        { id: 18, nama: "Rangga Adikara", nilai: [85, 81, 85, 76] },
        { id: 19, nama: "Sekar Ayu Lestari", nilai: [93, 89, 88, 84] },
        { id: 20, nama: "Tegar Wibowo", nilai: [99, 92, 96, 92] },
        { id: 21, nama: "Umar Hamidah", nilai: [81, 77, 81, 77] },
        { id: 22, nama: "Vania Kusuma", nilai: [89, 85, 89, 85] },
        { id: 23, nama: "Wira Setyawan", nilai: [97, 93, 97, 88] },
        { id: 24, nama: "Yudhistira Adi", nilai: [82, 78, 77, 73] },
        { id: 25, nama: "Zahra Amelia", nilai: [90, 81, 85, 81] },
        { id: 26, nama: "Bagas Prasetyo", nilai: [93, 89, 93, 89] },
        { id: 27, nama: "Aisyah Putri", nilai: [78, 74, 78, 74] },
        { id: 28, nama: "Rafi Mahendra", nilai: [86, 82, 86, 77] },
      ],
      pengumuman: [
        {
          id: 1,
          nama: "Ujian Akhir Semester",
          description: "Akan dilaksanakan pada tanggal 10 Oktober 2026",
          date: "29 September 2026",
        },
        {
          id: 2,
          nama: "Brief Proyek Poster",
          description:
            "Brief proyek poster untuk XI DKV A sudah dibagikan. Batas pengumpulan 1 Oktober 2026.",
          date: "26 September 2026",
        },
        {
          id: 3,
          nama: "Materi Copywriting",
          description: "Materi bab copywriting untuk media cetak sudah tersedia di halaman materi.",
          date: "20 September 2026",
        },
      ],
    },
    {
      id: 3,
      kelas: "XI RPL C",
      totalMurid: 30,
      materi: [
        {
          id: 1,
          title: "Belajar Teks Eksposisi",
          desc: "Mengenal teks eksposisi sebagai teks yang bertujuan menjelaskan suatu peristiwa atau gagasan secara sistematis, beserta tesis, rangkaian argumen, dan penegasan ulang.",
          attachedFiles: ["/materi/eksposisi-modul.pdf", "https://kemdikbud.go.id/teks-eksposisi"],
        },
        {
          id: 2,
          title: "Unsur Intrinsik Cerpen",
          desc: "Mempelajari lima unsur intrinsik cerpen — tokoh, penokohan, latar, konflik, dan amanat — beserta cara mengidentifikasi setiap unsur pada kutipan cerita pendek.",
          attachedFiles: ["/materi/cerpen-unsur.pdf", "/materi/cerpen-kisah-di-sekolah.docx"],
        },
        {
          id: 3,
          title: "Teks Pidato Persuasif",
          desc: "Struktur pembuka, isi, dan penutup teks pidato persuasif, disertai teknik kebahasaan persuasif dan cara menyusun data yang kuat untuk membahas isu lingkungan.",
          attachedFiles: ["https://id.wikipedia.org/wiki/Pidato_persuasif"],
        },
        {
          id: 4,
          title: "Membuat Resensi Buku",
          desc: "Panduan menulis resensi: identitas buku, sinopsis, kelebihan, dan kekurangan, serta cara memberi rekomendasi yang jujur berdasarkan pembacaan utuh.",
          attachedFiles: ["/materi/resensi-panduan.pdf", "/materi/contoh-resensi.pdf"],
        },
      ],
      tugas: [
        {
          id: 1,
          name: "Menulis Teks Eksposisi",
          deadline: "10 September 2026",
          completed: false,
          muridSelesai: 19,
        },
        {
          id: 2,
          name: "Analisis Unsur Intrinsik Cerpen",
          deadline: "12 Agustus 2026",
          completed: true,
          muridSelesai: 30,
        },
        {
          id: 3,
          name: "Membuat Teks Pidato Persuasif",
          deadline: "24 Agustus 2026",
          completed: true,
          muridSelesai: 25,
        },
        {
          id: 4,
          name: "Membuat Resensi Buku",
          deadline: "1 September 2026",
          completed: true,
          muridSelesai: 29,
        },
      ],
      dataMurid: [
        { id: 1, nama: "Sari Ramadhani", nilai: [87, 83, 87, 83] },
        { id: 2, nama: "Dika Prasetyo", nilai: [95, 91, 95, 91] },
        { id: 3, nama: "Laras Ayu", nilai: [100, 99, 100, 94] },
        { id: 4, nama: "Naufal Hidayat", nilai: [88, 84, 83, 79] },
        { id: 5, nama: "Bagja Wicaksono", nilai: [96, 87, 91, 87] },
        { id: 6, nama: "Cakra Wibowo", nilai: [99, 95, 99, 95] },
        { id: 7, nama: "Dian Anggraini", nilai: [84, 80, 84, 80] },
        { id: 8, nama: "Erlangga Saputra", nilai: [92, 88, 92, 83] },
        { id: 9, nama: "Fitria Wulandari", nilai: [100, 96, 95, 91] },
        { id: 10, nama: "Gilang Prakoso", nilai: [85, 76, 80, 76] },
        { id: 11, nama: "Hana Salsabila", nilai: [88, 84, 88, 84] },
        { id: 12, nama: "Indra Gunawan", nilai: [96, 92, 96, 92] },
        { id: 13, nama: "Jazmin Aulia", nilai: [100, 100, 100, 95] },
        { id: 14, nama: "Kenza Adriani", nilai: [89, 85, 84, 80] },
        { id: 15, nama: "Lukman Abdillah", nilai: [97, 88, 92, 88] },
        { id: 16, nama: "Martha Dewi", nilai: [100, 96, 100, 96] },
        { id: 17, nama: "Nadia Rahmadani", nilai: [85, 81, 85, 81] },
        { id: 18, nama: "Oscar Manurung", nilai: [93, 89, 92, 83] },
        { id: 19, nama: "Putri Anggraini", nilai: [100, 96, 95, 91] },
        { id: 20, nama: "Raka Adrianto", nilai: [85, 76, 80, 76] },
        { id: 21, nama: "Salma Nuraini", nilai: [88, 84, 88, 84] },
        { id: 22, nama: "Taufik Hidayat", nilai: [96, 92, 96, 92] },
        { id: 23, nama: "Uli Novitasari", nilai: [81, 77, 81, 72] },
        { id: 24, nama: "Vino Ardiansyah", nilai: [89, 85, 84, 80] },
        { id: 25, nama: "Wulan Puspitasari", nilai: [97, 88, 92, 88] },
        { id: 26, nama: "Yoga Pratama", nilai: [100, 96, 100, 96] },
        { id: 27, nama: "Zaki Hamzah", nilai: [85, 81, 85, 81] },
        { id: 28, nama: "Andra Wijaya", nilai: [93, 89, 93, 84] },
        { id: 29, nama: "Bunga Ayu", nilai: [100, 98, 96, 92] },
        { id: 30, nama: "Candra Kirana", nilai: [86, 77, 81, 77] },
      ],
      pengumuman: [
        {
          id: 1,
          nama: "Ujian Akhir Semester",
          description: "Akan dilaksanakan pada tanggal 10 Oktober 2026",
          date: "29 September 2026",
        },
        {
          id: 2,
          nama: "Jadwal remedial",
          description: "Remedial bagi siswa dengan nilai di bawah KKM 80 dilaksanakan Sabtu, 05.00 WIB.",
          date: "25 September 2026",
        },
        {
          id: 3,
          nama: "Pengumpulan Tugas",
          description: "Kumpulkan tugas sebelum 1 September 2026",
          date: "27 September 2026",
        },
      ],
    },
  ],
};

export type GuruClass = (typeof dummyGuruData.dataKelas)[number];

/** Look up one class by id — routes are `/teacher/home/[id]`. */
export function findClass(id: number): GuruClass | undefined {
  return dummyGuruData.dataKelas.find((c) => c.id === id);
}
